numpy practice -1

In [1]:
import numpy as np

a = np.array([[1,2,3],[4,5,6]])
b = np.array([10,20,30])

result = a + b
print(result)

[[11 22 33]
 [14 25 36]]


dimentional array

In [8]:
import numpy as np

arr_1d = np.array([1,2,3])
arr_2d = np.array([[1,2,3],[4,5,6]])
arr_3d = np.array([[1,2,3],[4,5,6],[7,8,9]])

print('1d Array:',arr_1d)
print('2d Array:',arr_2d)
print('3d Array:',arr_3d)

print('Broadcasted sum:', arr_1d + arr_2d)
print('Broadcasted sum:', arr_1d + arr_3d)

1d Array: [1 2 3]
2d Array: [[1 2 3]
 [4 5 6]]
3d Array: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Broadcasted sum: [[2 4 6]
 [5 7 9]]
Broadcasted sum: [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


broadcasting mismatch

In [11]:
import numpy as np

arr1 = np.array([[1,2,3],[4,5,6]])
arr2 = np.array([10,20])

print(arr1 + arr2)  #it will show value error because of the shapes of both array

Advanced Array Manipulation

In [14]:
import numpy as np

arr = np.arange(12)
print(arr)

reshaped = arr.reshape(3,-1)
print(reshaped)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


concatenation

In [17]:
import numpy as np

a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])


print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


splitting

In [21]:
import numpy as np

arr = np.arange(9).reshape(3,3)
print(arr)

result = np.hsplit(arr,1)
print(result)

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])]


Working with Random Numbers

In [30]:
import numpy as np

arr = np.random.rand(3,3)
print(arr)
arr = np.random.randn(3,3)
print(arr)
arr = np.random.randint(1,10,size=(3,3))
print(arr)

np.random.seed(42)
print(np.random.rand(2))

arr1 = np.array([1,2,3,4,5])
np.random.shuffle(arr1)
print(arr1)

[[0.15601864 0.15599452 0.05808361]
 [0.86617615 0.60111501 0.70807258]
 [0.02058449 0.96990985 0.83244264]]
[[-0.58087813 -0.52516981 -0.57138017]
 [-0.92408284 -2.61254901  0.95036968]
 [ 0.81644508 -1.523876   -0.42804606]]
[[3 7 4]
 [9 3 5]
 [3 7 5]]
[0.37454012 0.95071431]
[2 5 1 4 3]


Practical Application – Basic Data Analysis

In [38]:
import numpy as np

np.random.seed(42)
scores = np.random.randint(50,100, size=(10,3))
print(scores)

print('Mean per students:', np.mean(scores, axis=1))
print('Mean per subject:', np.mean(scores, axis=0))
print('Max score per subject:', np.max(scores, axis=0))
print('Min score per subject:', np.min(scores, axis=0))

[[88 78 64]
 [92 57 70]
 [88 68 72]
 [60 60 73]
 [85 89 73]
 [52 71 51]
 [73 93 79]
 [87 51 70]
 [82 61 71]
 [93 74 98]]
Mean per students: [76.66666667 73.         76.         64.33333333 82.33333333 58.
 81.66666667 69.33333333 71.33333333 88.33333333]
Mean per subject: [80.  70.2 72.1]
Max score per subject: [93 93 98]
Min score per subject: [52 51 51]


Masked Arrays

In [39]:
import numpy as np

data = np.array([1, -999, 3, -999, 5])
masked = np.ma.masked_values(data, -999)  # Mask -999 as invalid
print("Masked Array:", masked)
print("Mean (ignoring masked):", masked.mean())

Masked Array: [1 -- 3 -- 5]
Mean (ignoring masked): 3.0
