first coding pracrice in collab

In [ ]:
import numpy as np
print(np.__version__)

2.0.2


basic array practice

In [ ]:
import numpy as np
arr = np.array([1,2,3,4,5])
print('Array:', arr)
print(arr.shape)
print(np.mean(arr))
print(np.max(arr))
print(np.min(arr))

Array: [1 2 3 4 5]
(5,)
3.0
5
1


array creation

In [12]:
import numpy as np

zeroes = np.zeros((3,3))
print('Zeroes:',zeroes)

arr = np.arange(10).reshape(2,5)
print('Array: ', arr)

linspace = np.linspace(0 , 100 , 5)
print('linspace: ', linspace)

Zeroes: [[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
Array:  [[0 1 2 3 4]
 [5 6 7 8 9]]
linspace:  [  0.  25.  50.  75. 100.]


indexing and slicing

In [20]:
import numpy as np

arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print('Array: ', arr)

print('First row: ',arr[0, :])

print('Third row: ',arr[2, :])

print('First column: ', arr[: ,0])

print('Second column: ', arr[:,1])

print('Elements >5:', arr[arr>5])

Array:  [[1 2 3]
 [4 5 6]
 [7 8 9]]
First row:  [1 2 3]
Third row:  [7 8 9]
First column:  [1 4 7]
Second column:  [2 5 8]
Elements >5: [6 7 8 9]


array operations

In [23]:
import numpy as np

arr1 = np.array([1,2,3])
arr2 = np.array([4,5,6])

print('Addition:', arr1+arr2)
print('Subtraction:', arr1-arr2)
print('Multiplication:', arr1*arr2)
print('Division:', arr1/arr2)

print('Square:', arr1**2)
print('Square root:', np.sqrt(arr1))

print('Sum:', np.sum(arr1))
print('Mean:',np.mean(arr1))

Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]
Square: [1 4 9]
Square root: [1.         1.41421356 1.73205081]
Sum: 6
Mean: 2.0


linear algebra

In [27]:
import numpy as np

arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[5,6],[7,8]])

print('Dot product:', np.dot(arr1,arr2))

print('Determinant:',np.linalg.det(arr1))

print('Transpose:', np.transpose(arr2))

Dot product: [[19 22]
 [43 50]]
Determinant: -2.0000000000000004
Transpose: [[5 7]
 [6 8]]
